dataset:
  dataset_annotations: D:\ML_train_data\hagrid_hand_dataset #<path_to_annotations> # Path to annotations
  dataset_folder: D:\ML_train_data\hagrid_hand_dataset\hagrid_dataset_512 #<path_to_dataset> # Path to images
  phases: [train, test, val] #names of annotation directories
  targets:
    - call
    - fist
    - like
    - mute
    - ok
    - one
    - palm
    - peace
    - stop
    - three
    - no_gesture
